apiVersion: v1
kind: Namespace
metadata:
  name: k8s-web

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-view
  namespace: k8s-web
subjects:
- kind: ServiceAccount
  name: default
  namespace: k8s-web
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web
  namespace: k8s-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-web
  template:
    metadata:
      labels:
        app: k8s-web
    spec:
      containers:
      - name: k8s-web
        image: k8s-web-image
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-web
  namespace: k8s-web
spec:
  selector:
    app: k8s-web
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
